---
extends: default

ignore: |
  .venv/

rules:
  document-start: disable
  line-length:
    max: 160
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false  # GitHub Actions' `on:`
    level: error
  comments:
    level: warning
  comments-indentation: disable
